# Generated by Django 4.1.3 on 2023-01-06 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_animal_doctor_veterinaria_pages_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='pagina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppBlog.pages'),
        ),
    ]
