# Generated by Django 4.1.3 on 2023-01-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_remove_pages_blog_blog_pagina'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogs',
        ),
    ]
