# Generated by Django 4.1.3 on 2023-01-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_rename_blog_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='cuerpo',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='fecha',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='subtitulo',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
