# Generated by Django 4.1.3 on 2023-01-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_blogs_autor_alter_blogs_cuerpo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='pagina',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='descripcion',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
