# Generated by Django 4.1.3 on 2023-01-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_remove_blogs_pagina_alter_blogs_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
