# Generated by Django 4.1.3 on 2023-01-06 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_alter_blogs_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='pagina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppBlog.pages'),
        ),
    ]
