# Generated by Django 4.1.3 on 2023-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_blogs_pagina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='animal',
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
        migrations.DeleteModel(
            name='veterinaria',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='pagina',
        ),
        migrations.AddField(
            model_name='blogs',
            name='pagina_id',
            field=models.IntegerField(null=True),
        ),
    ]
