# Generated by Django 4.1.3 on 2023-01-10 02:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
