# Generated by Django 4.1.5 on 2023-01-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0012_alter_blogs_cuerpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.blogs')),
            ],
        ),
    ]
