# Generated by Django 4.1.5 on 2023-01-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_rename_uploads_imagen_remove_blogs_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
