# Generated by Django 4.1.5 on 2023-01-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0015_blogs_imagen_delete_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='imagen',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
